load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//tictactoe_astar:__subpackages__"])

cc_library(
    name = "renderer",
    srcs = ["renderer.cc"],
    hdrs = ["renderer.h"],
)
